version: '3.4'

networks:
  k6:
  grafana:

services:

  influxdb:
    image: influxdb:1.8
    container_name: influx
    networks:
      - k6
      - grafana
    ports:
      - "8085:8086"
    environment:
      - INFLUXDB_DB=myk6db

    
  grafana:
    image: grafana/grafana:latest
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
    networks:
      - grafana
    ports:
      - 3000:3000
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./provisioning/dashboards:/etc/grafana/provisioning/dashboards
    depends_on:
      - k6

  k6:
    image: grafana/k6:latest
    networks:
      - k6
    ports:
      - "6565:6565"
    environment:
      - K6_OUT=influxdb=http://influx:8086/myk6db
    volumes:
      - ./samples:/scripts

volumes:
  grafana-storage: